### ISSUE TITLE
Where can I find the installation documentation ?

### ISSUE THREAD

**Issue by killermouse0** [beezee/Bumper#3]
Hello there !

I'd like to give this a spin but I have absolutely no idea regarding how to install it and do the setup.

Is there a documentation somewhere ?

Many thanks in advance !

Stéphane

**Comment by peterjcarroll** [comment]
I'm also interested in this. What the status of this project? Is functional or still pretty early in development?

**Comment by beezee** [comment]
Sorry about this guys - project is functional, needs some refactoring around config options and then I have to bite down and write the docs. I'm going to try to get that done in the coming weeks.

In the meantime, try this:

1- clone, rake db:migrate, rake bumper:start
2- configure a supported email provider to point to the app as defined by the griddler gem (see https://robots.thoughtbot.com/handle-incoming-email-with-griddler) and update initializers/griddler and Gemfile as needed, (currently set for mandrill - https://github.com/wingrunr21/griddler-mandrill)
3- use the list of supported email formats here to email the app and have it return your message at the desired time - https://github.com/beezee/Bumper-deprecated

Let me know if any snags

**Comment by killermouse0** [comment]
Hi there,

Is a "mail to POST" service a requirement ? I had hoped that this was a fully self hosted solution (as I'm not going to send confidential emails to anywhere but home), and that I might feed emails from postfix into it for example.

Not possible, right ?

**Comment by leggewie** [comment]
I'm hoping for the same as @killermouse0 

Nudgemail works great for me so far, except that I'm uneasy about privacy.  I guess it would be good to have GPG-integration so that anything outside one's server is fully secure.

**Comment by leggewie** [comment]
Would love to hear a comment from @beezee

**Comment by killermouse0** [comment]
Time to give up :)
